name = "cake_sqlight"
description = "🎂Cake 🪶SQLite adapter which which passes PreparedStatements to the sqlight library for execution written in Gleam."
repo_url = "https://github.com/inoas/gleam-cake-sqlight"
category = ""
