name = "cors_builder"
description = "A CORS Builder, performing validation and injection of CORS for misp, wisp and any framework!"
repo_url = "https://github.com/ghivert/cors-builder"
category = "HTTP"
