name = "directories"
description = "A lightweight package to get standard locations of directories for temporary files, config, cache, etc."
repo_url = "https://github.com/ditherwither/directories"
category = ""
