name = "glailwind_merge"
description = "Utility function to efficiently merge Tailwind CSS classes in JS without style conflicts."
repo_url = "https://github.com/dinkelspiel/glailwind_merge"
category = ""
