name = "gleamy_structures"
description = "Data structures in pure Gleam! Including tree, heap, non empty list, map, set, and priority queue."
repo_url = "https://github.com/schurhammer/gleamy_structures/"
category = "Data Structures"
