name = "hardcache"
description = "Gleam module that provides primitives for caching key-value pairs in files and using files as caches."
repo_url = "https://github.com/katekyy/hardcache"
category = ""
