name = "hexdocs_offline"
description = "Download an offline version of the hexdocs of your projects dependencies to a local folder!"
repo_url = "https://github.com/daniellionel01/hexdocs_offline"
category = "Project Tooling"
