name = "howdy_authentication_cookies"
description = "An authentication library using cookies designed to work with the Howdy web server."
repo_url = "https://github.com/mikeyjones/project"
category = ""
