name = "opt_args_with_defs_for_gleam"
description = "Optional Arguments with Defaults for Gleam - A cursed workaround"
repo_url = "https://github.com/inoas/opt_args_with_defs_for_gleam"
category = ""
