name = "redraw"
description = "React bindings for Gleam! Supports everything modern React provides, with full Gleam Type-Checking system!"
repo_url = "https://github.com/ghivert/redraw"
category = "Frontend"
