name = "staff_ai"
description = "Become the CEO of your own AI workforce, efficiently managing countless intelligent agents with minimal resources."
repo_url = "https://github.com/chainyo/staff-ai"
category = ""
