name = "stdin"
description = "Provides a synchronous iterator for consuming stdin. It supports all the non-browser targets, Erlang, Node, Deno, and Bun."
repo_url = "https://github.com/olian04/gleam-stdin"
category = "Command Line"
